### ISSUE TITLE
Running Infinitely

### ISSUE THREAD

**Issue by compulshun** [ctsrc/Pgen#4]
Hey team,

I'm aware you haven't updated this in three years and I may not get a response. I'm wondering what I'd need to edit to allow the program to run infinitely, or until it's created every possible permutation.

Even the ability to run more than 999999999 iterations would be a bonus; I'm not familiar with rust programming at all though and my haphazard attempts at changing the integer value from u32 yielded no results.

Let me know if this is something you can help with!

Best regards,
Eythan

**Comment by ctsrc** [comment]
Hi,

You mentioned being able to run for 999,999,999 iterations. You can do that already if you want. The max value a `u32` can hold is 4,294,967,295.

If you want, you can instruct the program to run for as many as 4,294,967,295 iterations:

```zsh
pgen -k 4294967295
```

However, this program rolls the "dice" randomly, so if you run the program for many iterations it will eventually generate the same password two or more times in a single run.

Iterating over all possible permutations is pretty simple too, but not something this program has been designed to do. And if the number of words you want in the passphrase is high enough, you will certainly have to wait well beyond [the heat death of the universe](https://en.wikipedia.org/wiki/Heat_death_of_the_universe) :^)

If you are interested in permutations, you might want to check out the following two snippets of code that I wrote in some other languages years ago on another GitHub account:

- https://gist.github.com/yarwelp/1429851 written in Python
- https://gist.github.com/yarwelp/1403833 written in JavaScript

Those snippets do not relate directly to passwords or pass phrases. But the concept would be the same.

Closing this ticket as out of scope.
